FROM python:3
LABEL maintainer="fjs@usp.br"

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

#CMD [ "python", "./your-daemon-or-script.py" ]
CMD [ "bash" ]